package model.bean;
// Generated 11/06/2019 14:20:42 by Hibernate Tools 4.3.1



/**
 * Avaliacao generated by hbm2java
 */
public class Avaliacao  implements java.io.Serializable {


     private Integer avaid;
     private String avanome;
     private String avadesc;
     private String avacurso;
     private int avamat;

    public Avaliacao() {
    }

    public Avaliacao(String avanome, String avadesc, String avacurso, int avamat) {
       this.avanome = avanome;
       this.avadesc = avadesc;
       this.avacurso = avacurso;
       this.avamat = avamat;
    }
   
    public Integer getAvaid() {
        return this.avaid;
    }
    
    public void setAvaid(Integer avaid) {
        this.avaid = avaid;
    }
    public String getAvanome() {
        return this.avanome;
    }
    
    public void setAvanome(String avanome) {
        this.avanome = avanome;
    }
    public String getAvadesc() {
        return this.avadesc;
    }
    
    public void setAvadesc(String avadesc) {
        this.avadesc = avadesc;
    }
    public String getAvacurso() {
        return this.avacurso;
    }
    
    public void setAvacurso(String avacurso) {
        this.avacurso = avacurso;
    }
    public int getAvamat() {
        return this.avamat;
    }
    
    public void setAvamat(int avamat) {
        this.avamat = avamat;
    }




}


