package model.bean;
// Generated 11/06/2019 14:20:42 by Hibernate Tools 4.3.1



/**
 * Coletor generated by hbm2java
 */
public class Coletor  implements java.io.Serializable {


     private Integer colid;
     private String coltel;
     private String colcpfCnpj;
     private Integer colendid;
     private Integer tipcolid;

    public Coletor() {
    }

	
    public Coletor(String coltel, String colcpfCnpj) {
        this.coltel = coltel;
        this.colcpfCnpj = colcpfCnpj;
    }
    public Coletor(String coltel, String colcpfCnpj, Integer colendid, Integer tipcolid) {
       this.coltel = coltel;
       this.colcpfCnpj = colcpfCnpj;
       this.colendid = colendid;
       this.tipcolid = tipcolid;
    }
   
    public Integer getColid() {
        return this.colid;
    }
    
    public void setColid(Integer colid) {
        this.colid = colid;
    }
    public String getColtel() {
        return this.coltel;
    }
    
    public void setColtel(String coltel) {
        this.coltel = coltel;
    }
    public String getColcpfCnpj() {
        return this.colcpfCnpj;
    }
    
    public void setColcpfCnpj(String colcpfCnpj) {
        this.colcpfCnpj = colcpfCnpj;
    }
    public Integer getColendid() {
        return this.colendid;
    }
    
    public void setColendid(Integer colendid) {
        this.colendid = colendid;
    }
    public Integer getTipcolid() {
        return this.tipcolid;
    }
    
    public void setTipcolid(Integer tipcolid) {
        this.tipcolid = tipcolid;
    }




}


