package model.bean;
// Generated 11/06/2019 14:20:42 by Hibernate Tools 4.3.1



/**
 * Tipopessoa generated by hbm2java
 */
public class Tipopessoa  implements java.io.Serializable {


     private Integer tippid;
     private String tippdesc;
     private String tippnome;
     private String tipprazao;
     private String tippnomef;

    public Tipopessoa() {
    }

	
    public Tipopessoa(String tippdesc) {
        this.tippdesc = tippdesc;
    }
    public Tipopessoa(String tippdesc, String tippnome, String tipprazao, String tippnomef) {
       this.tippdesc = tippdesc;
       this.tippnome = tippnome;
       this.tipprazao = tipprazao;
       this.tippnomef = tippnomef;
    }
   
    public Integer getTippid() {
        return this.tippid;
    }
    
    public void setTippid(Integer tippid) {
        this.tippid = tippid;
    }
    public String getTippdesc() {
        return this.tippdesc;
    }
    
    public void setTippdesc(String tippdesc) {
        this.tippdesc = tippdesc;
    }
    public String getTippnome() {
        return this.tippnome;
    }
    
    public void setTippnome(String tippnome) {
        this.tippnome = tippnome;
    }
    public String getTipprazao() {
        return this.tipprazao;
    }
    
    public void setTipprazao(String tipprazao) {
        this.tipprazao = tipprazao;
    }
    public String getTippnomef() {
        return this.tippnomef;
    }
    
    public void setTippnomef(String tippnomef) {
        this.tippnomef = tippnomef;
    }




}


